import React, { useMemo, useState } from "react";

const opportunities = [
  { id: 1, type: "Internship", title: "Software Engineering Internship", org: "Opportunity Example", location: "Lagos, Nigeria", mode: "Hybrid", deadline: "Deadline varies", description: "Build practical software engineering experience through a professional internship opportunity." },
  { id: 2, type: "Scholarship", title: "International Study Scholarship", org: "Opportunity Example", location: "International", mode: "Fully Funded", deadline: "Deadline varies", description: "Explore funding support for students interested in studying internationally." },
  { id: 3, type: "Job", title: "Graduate Technology Role", org: "Opportunity Example", location: "Nigeria", mode: "Full-time", deadline: "Deadline varies", description: "A graduate technology opportunity designed for early-career professionals." }
];
const cats = ["Jobs","Scholarships","Internships","Fellowships","Grants","Competitions","Training","Volunteer","Remote Work"];
const guides = ["Build a strong CV","Apply with confidence","Find scholarships","Prepare for interviews"];
const field = {width:"100%",padding:12,border:"1px solid #d9e0ea",borderRadius:10,boxSizing:"border-box"};

function Modal({title,close,children}){return <div onMouseDown={e=>e.target===e.currentTarget&&close()} style={{position:"fixed",inset:0,zIndex:1000,background:"#0009",display:"grid",placeItems:"center",padding:16}}><div style={{background:"white",borderRadius:18,padding:24,width:"min(680px,100%)",maxHeight:"90vh",overflow:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 style={{margin:0}}>{title}</h2><button onClick={close} style={{border:0,borderRadius:8,fontSize:22}}>×</button></div>{children}</div></div>}

export default function App(){
 const [menu,setMenu]=useState(false),[filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[loc,setLoc]=useState(""),[saved,setSaved]=useState([]),[modal,setModal]=useState(null),[selected,setSelected]=useState(null),[toast,setToast]=useState("");
 const [login,setLogin]=useState({email:"",password:""}),[reg,setReg]=useState({name:"",email:"",password:""});
 const [cv,setCv]=useState({name:"",title:"",email:"",phone:"",summary:"",experience:"",education:"",projects:"",skills:""});
 const show=m=>{setToast(m);setTimeout(()=>setToast(""),2800)};
 const go=id=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:"smooth"})};
 const results=useMemo(()=>opportunities.filter(o=>(filter==="All"||o.type===filter)&&(!query||`${o.title} ${o.org} ${o.location}`.toLowerCase().includes(query.toLowerCase()))&&(!loc||o.location.toLowerCase().includes(loc.toLowerCase()))),[filter,query,loc]);
 const submit=e=>{e.preventDefault();if(!login.email||!login.password)return show("Enter your email and password.");setModal(null);show("Login interface is ready. Connect Supabase Auth for real accounts.")};
 const register=e=>{e.preventDefault();if(!reg.name||!reg.email||reg.password.length<8)return show("Use your name, email and a password of at least 8 characters.");setModal(null);show("Registration interface is ready. Connect Supabase Auth for real accounts.")};
 const saveCV=()=>{localStorage.setItem("oh_cv",JSON.stringify(cv));show("CV saved on this device.")};
 const openCV=()=>{const x=localStorage.getItem("oh_cv");if(x)setCv(JSON.parse(x));setModal("cv")};
 return <div style={{fontFamily:"Inter,Arial,sans-serif",color:"#101827"}}>
 <style>{`*{box-sizing:border-box}body{margin:0}button{cursor:pointer;font:inherit}.wrap{width:min(1160px,calc(100% - 30px));margin:auto}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}@media(max-width:800px){.links{display:none!important}.mobile{display:block!important}.grid3,.grid4{grid-template-columns:1fr}.heroGrid{grid-template-columns:1fr!important}.search{grid-template-columns:1fr!important}.trust{grid-template-columns:1fr 1fr!important}}@media print{body *{visibility:hidden}.printcv,.printcv *{visibility:visible}.printcv{position:absolute;left:0;top:0;width:100%}}`}</style>
 {toast&&<div style={{position:"fixed",top:15,left:"50%",transform:"translateX(-50%)",zIndex:2000,background:"#071120",color:"white",padding:"12px 18px",borderRadius:10}}>{toast}</div>}
 <header style={{position:"sticky",top:0,zIndex:500,background:"white",borderBottom:"1px solid #eee"}}><div className="wrap" style={{minHeight:68,display:"flex",alignItems:"center",justifyContent:"space-between"}}>
 <button onClick={()=>go("home")} style={{border:0,background:0,fontWeight:800,fontSize:20}}><b style={{background:"#1769ff",color:"white",padding:"6px 9px",borderRadius:8}}>O</b> Opportunity<span style={{color:"#1769ff"}}>Hub</span></button>
 <nav className="links" style={{display:"flex",gap:15,alignItems:"center"}}>{[["Home",()=>go("home")],["Jobs",()=>{setFilter("Job");go("opportunities")}],["Internships",()=>{setFilter("Internship");go("opportunities")}],["Scholarships",()=>{setFilter("Scholarship");go("opportunities")}],["Opportunities",()=>go("categories")],["CV Builder",openCV],["Resources",()=>go("resources")}]].map(([x,f])=><button key={x} onClick={f} style={{border:0,background:0}}>{x}</button>)}<button onClick={()=>setModal("login")} style={{border:0,background:0,color:"#1769ff"}}>Login</button><button onClick={()=>setModal("register")} style={{border:0,background:"#1769ff",color:"white",padding:"10px 14px",borderRadius:9}}>Get Started</button></nav>
 <button className="mobile" onClick={()=>setMenu(!menu)} style={{display:"none",border:0,background:"#eef3fa",padding:10,borderRadius:9}}>☰</button></div>{menu&&<div style={{padding:12}}>{["Home","Jobs","Internships","Scholarships","Opportunities","CV Builder","Resources","Login","Get Started"].map(x=><button key={x} onClick={()=>x==="CV Builder"?openCV():x==="Login"?setModal("login"):x==="Get Started"?setModal("register"):go(x==="Opportunities"?"categories":x.toLowerCase())} style={{display:"block",width:"100%",padding:11,border:0,textAlign:"left"}}>{x}</button>)}</div>}</header>
 <section id="home" style={{background:"linear-gradient(135deg,#f5f8ff,#eaf2ff)",padding:"70px 0"}}><div className="wrap heroGrid" style={{display:"grid",gridTemplateColumns:"1.15fr .85fr",gap:45,alignItems:"center"}}><div><span style={{color:"#1769ff",fontWeight:800}}>✦ Your next opportunity starts here</span><h1 style={{fontSize:"clamp(42px,6vw,70px)",lineHeight:1,margin:"18px 0"}}>Find your next <span style={{color:"#1769ff"}}>opportunity.</span></h1><p style={{fontSize:17,lineHeight:1.7,color:"#627087"}}>Discover jobs, internships, scholarships, grants, fellowships, training programs and more—all in one trusted platform.</p><div className="search" style={{display:"grid",gridTemplateColumns:"1fr 150px 110px",gap:7,background:"white",padding:9,borderRadius:15,boxShadow:"0 10px 30px #183b7a12"}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What are you looking for?" style={{...field,border:0,background:"#f7f9fc"}}/><select value={loc} onChange={e=>setLoc(e.target.value)} style={{...field,border:0,background:"#f7f9fc"}}><option value="">Any location</option><option>Nigeria</option><option>Lagos</option><option>Abuja</option><option>International</option></select><button onClick={()=>go("opportunities")} style={{border:0,borderRadius:9,background:"#1769ff",color:"white",fontWeight:800}}>Search</button></div></div><div style={{background:"#081324",padding:18,borderRadius:22,color:"white"}}>{[["💼","Jobs"],["🎓","Scholarships"],["🚀","Internships"],["🌍","Remote Opportunities"]].map(([i,x])=><button key={x} onClick={()=>{setFilter(x==="Jobs"?"Job":x==="Internships"?"Internship":x==="Scholarships"?"Scholarship":"All");go("opportunities")}} style={{width:"100%",display:"flex",gap:12,alignItems:"center",padding:15,marginBottom:9,border:"1px solid #24324a",borderRadius:12,background:"#111d32",color:"white",textAlign:"left"}}><span>{i}</span><b>{x}</b><span style={{marginLeft:"auto"}}>→</span></button>)}<p style={{color:"#9aa6ba"}}>Built around one simple idea.<b style={{display:"block",color:"white"}}>Make opportunity easier to find.</b></p></div></div></section>
 <section style={{padding:"25px 0",borderBottom:"1px solid #eee"}}><div className="wrap trust" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:15}}>{[["One platform","Multiple opportunity types"],["Opportunity-first","Designed around discovery"],["Trust focused","Clear information"],["Built for mobile","Made for everyday users"]].map(x=><div key={x[0]}><b style={{display:"block"}}>{x[0]}</b><small style={{color:"#718096"}}>{x[1]}</small></div>)}</div></section>
 <section id="categories" style={{padding:"70px 0"}}><div className="wrap"><small style={{color:"#1769ff",fontWeight:800}}>EXPLORE</small><h2 style={{fontSize:38}}>Opportunities for your next move.</h2><div className="grid3">{cats.map(x=><button key={x} onClick={()=>{setFilter(x==="Jobs"?"Job":x==="Internships"?"Internship":x==="Scholarships"?"Scholarship":"All");go("opportunities")}} style={{textAlign:"left",padding:20,minHeight:120,background:"white",border:"1px solid #e4e9f0",borderRadius:14}}><b>{x}</b><p style={{color:"#718096",fontSize:13}}>Explore {x.toLowerCase()} opportunities.</p><span style={{color:"#1769ff"}}>View →</span></button>)}</div></div></section>
 <section id="opportunities" style={{padding:"70px 0",background:"#f7f9fc"}}><div className="wrap"><small style={{color:"#1769ff",fontWeight:800}}>DISCOVER</small><h2 style={{fontSize:38}}>Explore opportunities.</h2><div style={{display:"flex",gap:7,flexWrap:"wrap",marginBottom:22}}>{["All","Job","Internship","Scholarship"].map(x=><button key={x} onClick={()=>setFilter(x)} style={{border:"1px solid #dce3ec",background:filter===x?"#1769ff":"white",color:filter===x?"white":"#334155",padding:"9px 13px",borderRadius:99}}>{x}</button>)}</div><div className="grid3">{results.map(o=><article key={o.id} style={{background:"white",border:"1px solid #e3e8ef",borderRadius:16,padding:19}}><div style={{display:"flex",justifyContent:"space-between"}}><b style={{background:"#101827",color:"white",padding:10,borderRadius:9}}>O</b><button onClick={()=>setSaved(s=>s.includes(o.id)?s.filter(x=>x!==o.id):[...s,o.id])} style={{border:"1px solid #ddd",background:"white",borderRadius:8}}>{saved.includes(o.id)?"♥":"♡"}</button></div><small style={{display:"inline-block",marginTop:15,color:"#1769ff",fontWeight:800}}>{o.type.toUpperCase()}</small><h3>{o.title}</h3><b style={{fontSize:13,color:"#596579"}}>{o.org}</b><p style={{color:"#687386",lineHeight:1.6,fontSize:13}}>{o.description}</p><small>📍 {o.location} · {o.mode}</small><div style={{borderTop:"1px solid #eee",marginTop:15,paddingTop:12,display:"flex",justifyContent:"space-between",alignItems:"center"}}><small>Deadline: <b>{o.deadline}</b></small><button onClick={()=>setSelected(o)} style={{border:0,background:"#1769ff",color:"white",padding:"9px 12px",borderRadius:8,fontWeight:800}}>View →</button></div></article>)}</div>{!results.length&&<p>No opportunities found. Clear your search or filters.</p>}</div></section>
 <section style={{background:"#081324",color:"white",padding:"75px 0"}}><div className="wrap heroGrid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:40,alignItems:"center"}}><div><small style={{color:"#4c8dff",fontWeight:800}}>CAREER TOOLS</small><h2 style={{fontSize:42}}>Build a CV that gets you noticed.</h2><p style={{color:"#aab5c6",lineHeight:1.7}}>Create a professional CV with OpportunityHub. Add your experience, education, projects and skills, then prepare it for applications.</p><button onClick={openCV} style={{border:0,background:"#1769ff",color:"white",padding:"13px 18px",borderRadius:10,fontWeight:800}}>Build My CV</button></div><div style={{background:"white",color:"#111",padding:28,borderRadius:8,minHeight:300}}><b style={{fontSize:20}}>Your Professional CV</b><hr/><p>Profile</p><p>Experience</p><p>Education</p><p>Projects</p><p>Skills</p></div></div></section>
 <section id="resources" style={{padding:"70px 0"}}><div className="wrap"><small style={{color:"#1769ff",fontWeight:800}}>CAREER RESOURCES</small><h2 style={{fontSize:38}}>Get better at finding opportunities.</h2><div className="grid4">{guides.map(x=><button key={x} onClick={()=>show("Career guide ready — add the full article when you are ready.")} style={{textAlign:"left",border:0,background:"#f5f6f8",borderRadius:14,padding:20,minHeight:160}}><small style={{color:"#1769ff",fontWeight:800}}>GUIDE</small><h3>{x}</h3><p style={{color:"#687386",fontSize:13}}>Practical guidance to help you prepare and apply.</p></button>)}</div></div></section>
 <section style={{background:"#f7f9fc",padding:"55px 0"}}><div className="wrap" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:30}}><div><small style={{color:"#1769ff",fontWeight:800}}>CREATOR</small><h2>Created by Ojattah Wisdom</h2><p style={{color:"#687386",lineHeight:1.7}}>OpportunityHub was created to make opportunities easier for students, graduates and professionals to discover.</p></div><div><h3>How OpportunityHub can make money</h3><p style={{color:"#687386",lineHeight:1.7}}>Future revenue can come from verified featured listings, employer plans, sponsored opportunities, premium CV tools and advertising such as AdSense after the site has useful original content and traffic.</p><button onClick={()=>show("Partner listings can be connected to a real payment system later.")} style={{border:0,background:"#1769ff",color:"white",padding:"11px 15px",borderRadius:9}}>Partner with us</button></div></div></section>
 <footer style={{background:"#071120",color:"white",padding:"35px 0"}}><div className="wrap"><b style={{fontSize:20}}>Opportunity<span style={{color:"#4c8dff"}}>Hub</span></b><p style={{color:"#9aa6ba"}}>Helping students, graduates and professionals discover their next opportunity.</p><div style={{borderTop:"1px solid #1d2a40",paddingTop:18,color:"#9aa6ba"}}>Created by <b style={{color:"white"}}>Ojattah Wisdom</b> · © 2026 OpportunityHub</div></div></footer>
 {selected&&<Modal title={selected.title} close={()=>setSelected(null)}><p><b>{selected.org}</b></p><p>📍 {selected.location} · {selected.mode}</p><p><b>Deadline:</b> {selected.deadline}</p><p style={{lineHeight:1.7}}>{selected.description}</p><h3>About this opportunity</h3><p>This is a sample listing. Replace it with a verified opportunity and application URL before publishing it as a real listing.</p><button onClick={()=>show("Application link will be added when this opportunity is connected to its verified source.")} style={{border:0,background:"#1769ff",color:"white",padding:12,borderRadius:9}}>Apply / Visit opportunity</button></Modal>}
 {modal==="login"&&<Modal title="Login to OpportunityHub" close={()=>setModal(null)}><form onSubmit={submit} style={{display:"grid",gap:12,marginTop:18}}><input type="email" placeholder="Email address" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} style={field}/><input type="password" placeholder="Password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} style={field}/><button style={{border:0,background:"#1769ff",color:"white",padding:12,borderRadius:9}}>Login</button></form><p style={{fontSize:12,color:"#687386"}}>Frontend is ready. Real authentication requires connecting Supabase Auth.</p></Modal>}
 {modal==="register"&&<Modal title="Create your account" close={()=>setModal(null)}><form onSubmit={register} style={{display:"grid",gap:12,marginTop:18}}><input placeholder="Full name" value={reg.name} onChange={e=>setReg({...reg,name:e.target.value})} style={field}/><input type="email" placeholder="Email address" value={reg.email} onChange={e=>setReg({...reg,email:e.target.value})} style={field}/><input type="password" placeholder="Password (8+ characters)" value={reg.password} onChange={e=>setReg({...reg,password:e.target.value})} style={field}/><button style={{border:0,background:"#1769ff",color:"white",padding:12,borderRadius:9}}>Create account</button></form></Modal>}
 {modal==="cv"&&<Modal title="Create your professional CV" close={()=>setModal(null)}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{[["name","Full name"],["title","Professional title"],["email","Email"],["phone","Phone"],["summary","Professional summary"],["experience","Experience"],["education","Education"],["projects","Projects"],["skills","Skills" ]].map(([k,p])=><textarea key={k} placeholder={p} rows={k==="summary"||k==="experience"||k==="projects"?4:1} value={cv[k]} onChange={e=>setCv({...cv,[k]:e.target.value})} style={field}/>)}</div><div style={{display:"flex",gap:8,marginTop:12}}><button onClick={saveCV} style={{border:0,background:"#1769ff",color:"white",padding:11,borderRadius:9}}>Save CV</button><button onClick={()=>window.print()} style={{border:"1px solid #ddd",background:"white",padding:11,borderRadius:9}}>Print / Save PDF</button></div><div className="printcv" style={{marginTop:20,border:"1px solid #ddd",padding:22}}><h1>{cv.name||"Your Name"}</h1><b>{cv.title||"Professional Title"}</b><p>{cv.email} {cv.phone&&` · ${cv.phone}`}</p>{[["Profile",cv.summary],["Experience",cv.experience],["Education",cv.education],["Projects",cv.projects],["Skills",cv.skills]].map(([h,v])=>v&&<div key={h}><h3>{h}</h3><p style={{whiteSpace:"pre-wrap",lineHeight:1.6}}>{v}</p></div>)}</div></Modal>}
 </div>;
}
